use_frameworks!
#  Created by Tom Stall <mtm<@>mountaintom<.>com> on 08/08/2017.
#  Copyright (c) 2017 Tom Stall. All rights reserved.

target 'TensorFlowServing-InceptionClient_Example' do
  pod 'TensorFlowServing-InceptionClient', :path => '../'
  pod 'PodAsset', '~> 0.22'

  target 'TensorFlowServing-InceptionClient_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
